name: deploy exercise
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout git repo
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run lint
              run: npm run lint

            