name: maestro

on: 
  workflow_call:
    inputs:
      delete:
        required: true
        type: string
        default: "true"

jobs:
    job1:
      uses: ./.github/workflows/reusable.yml
      with:
        teste: ${{ inputs.delete }}
    job2:
      if: (inputs.delete != 'true')
      uses: ./.github/workflows/reusable.yml
    job3:
      uses: ./.github/workflows/reusable.yml            
    job4:
      uses: ./.github/workflows/reusable.yml