name: maestro

on: 
  workflow_call:
    inputs:
      delete:
        required: true
        type: string
        default: "true"
      keep:
        required: true
        type: string
        default: "false"
      create:
        required: true
        type: string
        default: "true"
jobs:
    job1:
      uses: ./.github/workflows/reusable.yml
      with:
        teste: ${{ inputs.delete }}
    job2:      
      uses: ./.github/workflows/reusable_1.yml
    job3:
      needs: job2
      if: (inputs.delete == 'true') && (inputs.create == 'false' || inputs.keep == 'true')
      uses: ./.github/workflows/reusable_2.yml            
    job4:
      needs: job2
      uses: ./.github/workflows/reusable_3.yml
      with:
        teste: ${{ needs.job2.result }}
    job5:
      needs: job2
      uses: ./.github/workflows/reusable_4.yml
      with:
        teste: ${{ needs.job2.result }}