name: validando trigger
on:
    pull_request:
        types: 
            - closed
        branches:
            - develop

jobs:
    trigger-pr:
        runs-on: ubuntu-latest
        steps:
            - name: teste
              run: echo "Vai corinthians!!!"